"""users table add col phone_number

Revision ID: 856452f11278
Revises: 505748e3c7cb
Create Date: 2022-04-18 14:30:40.972560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '856452f11278'
down_revision = '505748e3c7cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
